language: r
r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

branches:
  only:
    - master
    - development
    - rc

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE, ...=list(quiet=FALSE))'
